/**
 * Void Survivor - Armas, Evoluciones, Mejoras y Sinergias Secretas
 * 100% en Español
 */

import { WeaponId, EvolvedWeaponId, WeaponDef, EvolvedWeaponDef, UpgradeDef, SynergyDef, Rarity } from './types';

export const WEAPON_DEFINITIONS: Record<WeaponId, WeaponDef> = {
  PLASMA_BLASTER: {
    id: 'PLASMA_BLASTER',
    name: 'Cañón de Pulsos',
    description: 'Pulsos de energía ultrarrápidos con núcleo blanco brillante y estelas de plasma cyan.',
    icon: '⚡',
    color: '#38bdf8',
    baseCooldown: 0.22,
    baseDamage: 24,
    range: 750,
    projectileSpeed: 680,
    projectileSize: 5,
    pierce: 1,
    evolutionRequiredUpgrade: 'ENERGY_CORE',
    evolutionResult: 'SUPERNOVA_CANNON',
  },
  RAILGUN: {
    id: 'RAILGUN',
    name: 'Cañón de Riel Cinético',
    description: 'Proyectil de hipervelocidad que atraviesa múltiples naves enemigas en línea recta.',
    icon: '🎯',
    color: '#a855f7',
    baseCooldown: 1.25,
    baseDamage: 85,
    range: 850,
    projectileSpeed: 1100,
    projectileSize: 6,
    pierce: 4,
    evolutionRequiredUpgrade: 'CRITICAL_CORE',
    evolutionResult: 'VOID_LANCE',
  },
  MISSILE_PODS: {
    id: 'MISSILE_PODS',
    name: 'Misiles Enjambre',
    description: 'Salva de cohetes guiados con sensores de proximidad y detonaciones de área.',
    icon: '🚀',
    color: '#f97316',
    baseCooldown: 1.5,
    baseDamage: 45,
    range: 750,
    projectileSpeed: 380,
    projectileSize: 6,
    pierce: 1,
    evolutionRequiredUpgrade: 'HOMING_CHIP',
    evolutionResult: 'DOOMSDAY_SALVO',
  },
  COMBAT_DRONES: {
    id: 'COMBAT_DRONES',
    name: 'Drones de Combate',
    description: 'Drones de escolta autónomos que orbitan la nave e interceptan amenazas automáticamente.',
    icon: '🛸',
    color: '#10b981',
    baseCooldown: 0.65,
    baseDamage: 28,
    range: 520,
    projectileSpeed: 540,
    projectileSize: 4,
    pierce: 1,
    evolutionRequiredUpgrade: 'AI_CORE',
    evolutionResult: 'OMEGA_SWARM',
  },
  SPREAD_SHOT: {
    id: 'SPREAD_SHOT',
    name: 'Dispersor de Metralla',
    description: 'Ráfaga de amplio arco con metralla perforante, devastadora a corta distancia.',
    icon: '💥',
    color: '#eab308',
    baseCooldown: 0.95,
    baseDamage: 32,
    range: 500,
    projectileSpeed: 500,
    projectileSize: 5,
    pierce: 2,
    evolutionRequiredUpgrade: 'BOUNCE_LENS',
    evolutionResult: 'STARFALL_BARRAGE',
  },
  TESLA_COIL: {
    id: 'TESLA_COIL',
    name: 'Emisor Tesla Ionizado',
    description: 'Descargas de alto voltaje en arco que saltan entre grupos de naves hostiles.',
    icon: '⚡',
    color: '#06b6d4',
    baseCooldown: 1.1,
    baseDamage: 38,
    range: 580,
    projectileSpeed: 850,
    projectileSize: 5,
    pierce: 3,
    evolutionRequiredUpgrade: 'OVERLOAD_CELL',
    evolutionResult: 'ARCLIGHT_STORM',
  },
};

export const EVOLVED_WEAPON_DEFINITIONS: Record<EvolvedWeaponId, EvolvedWeaponDef> = {
  SUPERNOVA_CANNON: {
    id: 'SUPERNOVA_CANNON',
    name: 'Cañón Supernova',
    baseWeaponId: 'PLASMA_BLASTER',
    requiredUpgradeId: 'ENERGY_CORE',
    description: 'Condensa micro-núcleos estelares que estallan en colosales llamaradas de plasma.',
    icon: '🌟',
    color: '#f59e0b',
    glowColor: 'rgba(245, 158, 11, 0.9)',
    cooldown: 0.35,
    damage: 135,
    projectileSpeed: 560,
    pierce: 3,
    specialEffect: 'EXPLODING_STELLAR_CORES',
  },
  VOID_LANCE: {
    id: 'VOID_LANCE',
    name: 'Lanza del Vacío',
    baseWeaponId: 'RAILGUN',
    requiredUpgradeId: 'CRITICAL_CORE',
    description: 'Haz de singularidad gravitacional instantáneo que pulveriza columnas enteras.',
    icon: '🌌',
    color: '#c084fc',
    glowColor: 'rgba(192, 132, 252, 0.95)',
    cooldown: 0.95,
    damage: 280,
    projectileSpeed: 1800,
    pierce: 99,
    specialEffect: 'INSTANT_PIERCE_SINGULARITY',
  },
  DOOMSDAY_SALVO: {
    id: 'DOOMSDAY_SALVO',
    name: 'Salva del Juicio Final',
    baseWeaponId: 'MISSILE_PODS',
    requiredUpgradeId: 'HOMING_CHIP',
    description: 'Lanza microojivas termonucleares en racimo con detonaciones en cadena.',
    icon: '☢️',
    color: '#ef4444',
    glowColor: 'rgba(239, 68, 68, 0.9)',
    cooldown: 1.1,
    damage: 160,
    projectileSpeed: 460,
    pierce: 1,
    specialEffect: 'CLUSTER_NUKE_DETONATIONS',
  },
  OMEGA_SWARM: {
    id: 'OMEGA_SWARM',
    name: 'Enjambre Omega',
    baseWeaponId: 'COMBAT_DRONES',
    requiredUpgradeId: 'AI_CORE',
    description: 'Escuadrón de nanodrones sobreacelerados disparando ráfagas continuas coordinadas.',
    icon: '🛸',
    color: '#34d399',
    glowColor: 'rgba(52, 211, 153, 0.9)',
    cooldown: 0.28,
    damage: 65,
    projectileSpeed: 700,
    pierce: 2,
    specialEffect: 'SYNCHRONIZED_RAPID_LASERS',
  },
  STARFALL_BARRAGE: {
    id: 'STARFALL_BARRAGE',
    name: 'Lluvia Estelar Prismática',
    baseWeaponId: 'SPREAD_SHOT',
    requiredUpgradeId: 'BOUNCE_LENS',
    description: 'Tormenta de fragmentos reflectantes que rebotan violentamente contra objetivos.',
    icon: '🌠',
    color: '#f43f5e',
    glowColor: 'rgba(244, 63, 94, 0.9)',
    cooldown: 0.7,
    damage: 95,
    projectileSpeed: 640,
    pierce: 4,
    specialEffect: 'RICOCHETING_PRISM_FLAK',
  },
  ARCLIGHT_STORM: {
    id: 'ARCLIGHT_STORM',
    name: 'Tormenta de Rayos de Arco',
    baseWeaponId: 'TESLA_COIL',
    requiredUpgradeId: 'OVERLOAD_CELL',
    description: 'Red perpetua de relámpagos ionizados que une y electrocuta a todas las naves en pantalla.',
    icon: '⚡',
    color: '#38bdf8',
    glowColor: 'rgba(56, 189, 248, 0.95)',
    cooldown: 0.65,
    damage: 110,
    projectileSpeed: 1100,
    pierce: 6,
    specialEffect: 'INFINITE_CHAIN_LIGHTNING',
  },
};

export const UPGRADE_CATALOG: UpgradeDef[] = [
  // Comunes
  {
    id: 'TITANIUM_PLATING',
    name: 'Blindaje de Titanio',
    description: '+25 Integridad máxima de casco y +1 Reducción de blindaje.',
    rarity: 'COMMON',
    category: 'DEFENSIVE',
    icon: '🛡️',
    maxLevel: 5,
    statEffects: { maxHp: 25, armor: 1 },
  },
  {
    id: 'HYPER_THRUSTER',
    name: 'Propulsores Iónicos',
    description: '+12% Velocidad sub-luz y mayor maniobrabilidad.',
    rarity: 'COMMON',
    category: 'UTILITY',
    icon: '🚀',
    maxLevel: 5,
    statEffects: { speed: 30 },
  },
  {
    id: 'WEAPON_CALIBRATION',
    name: 'Calibrador de Puntería',
    description: '+10% Cadencia de disparo en todas las baterías de armamento.',
    rarity: 'COMMON',
    category: 'OFFENSIVE',
    icon: '🎯',
    maxLevel: 5,
    statEffects: { fireRateMult: 0.1 },
  },
  {
    id: 'FLUX_AMPLIFIER',
    name: 'Amplificador de Flujo',
    description: '+15% Daño total infligido a naves enemigas.',
    rarity: 'COMMON',
    category: 'OFFENSIVE',
    icon: '💥',
    maxLevel: 5,
    statEffects: { damageMult: 0.15 },
  },
  {
    id: 'GRAVITY_FUNNEL',
    name: 'Embudo Gravitatorio',
    description: '+35% Radio de atracción de cristales de XP y materia del vacío.',
    rarity: 'COMMON',
    category: 'UTILITY',
    icon: '🧲',
    maxLevel: 5,
    statEffects: { pickupRadius: 50 },
  },

  // Raras (Claves para evoluciones)
  {
    id: 'ENERGY_CORE',
    name: 'Núcleo de Energía',
    description: '+20% Daño y desbloquea la evolución del CAÑÓN SUPERNOVA.',
    rarity: 'RARE',
    category: 'CORE',
    icon: '🔮',
    maxLevel: 3,
    statEffects: { damageMult: 0.2 },
    evolutionFor: 'PLASMA_BLASTER',
  },
  {
    id: 'CRITICAL_CORE',
    name: 'Núcleo Crítico',
    description: '+12% Probabilidad crítica, +30% Daño crítico y desbloquea LANZA DEL VACÍO.',
    rarity: 'RARE',
    category: 'CORE',
    icon: '👁️',
    maxLevel: 3,
    statEffects: { critChance: 0.12, critMult: 0.3 },
    evolutionFor: 'RAILGUN',
  },
  {
    id: 'HOMING_CHIP',
    name: 'Matriz de Puntería',
    description: '+20% Velocidad de misiles, +1 Perforación y desbloquea SALVA DEL JUICIO FINAL.',
    rarity: 'RARE',
    category: 'CORE',
    icon: '🛰️',
    maxLevel: 3,
    statEffects: { pierce: 1 },
    evolutionFor: 'MISSILE_PODS',
  },
  {
    id: 'AI_CORE',
    name: 'Núcleo IA Autónomo',
    description: '+15% Cadencia, +1 Dron adicional y desbloquea ENJAMBRE OMEGA.',
    rarity: 'RARE',
    category: 'CORE',
    icon: '🧠',
    maxLevel: 3,
    statEffects: { fireRateMult: 0.15 },
    evolutionFor: 'COMBAT_DRONES',
  },
  {
    id: 'BOUNCE_LENS',
    name: 'Lente de Refracción',
    description: '+2 Perforaciones de proyectil y desbloquea LLUVIA ESTELAR.',
    rarity: 'RARE',
    category: 'CORE',
    icon: '💎',
    maxLevel: 3,
    statEffects: { pierce: 2 },
    evolutionFor: 'SPREAD_SHOT',
  },
  {
    id: 'OVERLOAD_CELL',
    name: 'Condensador de Sobrecarga',
    description: '+20% Área de efecto, +1 Salto eléctrico y desbloquea TORMENTA DE RAYOS.',
    rarity: 'RARE',
    category: 'CORE',
    icon: '⚡',
    maxLevel: 3,
    statEffects: { damageMult: 0.15 },
    evolutionFor: 'TESLA_COIL',
  },
  {
    id: 'HEX_SHIELD_ARRAY',
    name: 'Generador de Escudo Hexagonal',
    description: '+40 Capacidad de escudo y +4/s Regeneración más veloz.',
    rarity: 'RARE',
    category: 'DEFENSIVE',
    icon: '🛡️',
    maxLevel: 4,
    statEffects: { maxShield: 40, shieldRegen: 4 },
  },

  // Épicas
  {
    id: 'MULTI_BARREL_FORGE',
    name: 'Ensamblaje Multicañón',
    description: '+1 Proyectil adicional en todas las salvas principales.',
    rarity: 'EPIC',
    category: 'OFFENSIVE',
    icon: '🔱',
    maxLevel: 2,
    statEffects: { extraProjectiles: 1 },
  },
  {
    id: 'NANITE_RECONSTRUCTOR',
    name: 'Nube de Nanitos Reparadores',
    description: 'Regenera pasivamente 3 puntos de casco por segundo.',
    rarity: 'EPIC',
    category: 'DEFENSIVE',
    icon: '🧪',
    maxLevel: 3,
    behaviorTag: 'NANITE_REPAIR',
  },
  {
    id: 'CHRONO_ACCELERATOR',
    name: 'Motor de Distorsión Crono',
    description: 'Reduce el enfriamiento del impulso en 40% y otorga 1s de invulnerabilidad.',
    rarity: 'EPIC',
    category: 'UTILITY',
    icon: '⏳',
    maxLevel: 2,
    behaviorTag: 'WARP_DASH',
  },

  // Legendarias
  {
    id: 'SINGULARITY_CATALYZER',
    name: 'Catalizador de Singularidad',
    description: 'Los élites destruidos generan un vórtice gravitatorio que aplasta enemigos cercanos.',
    rarity: 'LEGENDARY',
    category: 'CORE',
    icon: '🌀',
    maxLevel: 1,
    behaviorTag: 'DEATH_VORTEX',
  },
  {
    id: 'OVERCHARGE_REACTOR',
    name: 'Reactor de Punto Cero Sobrecargado',
    description: 'Al agotarse el escudo, emite una onda expansiva de 360° que causa 200 de daño.',
    rarity: 'LEGENDARY',
    category: 'CORE',
    icon: '💥',
    maxLevel: 1,
    behaviorTag: 'SHIELD_NOVA',
  },
  {
    id: 'EXECUTIONER_PROTOCOLS',
    name: 'Protocolos del Verdugo',
    description: 'Los golpes críticos aniquilan instantáneamente a enemigos regulares con menos del 30% de vida.',
    rarity: 'LEGENDARY',
    category: 'CORE',
    icon: '☠️',
    maxLevel: 1,
    behaviorTag: 'CRIT_EXECUTE',
  },

  // Rango Vacío (Nivel Supremo)
  {
    id: 'VOID_ENTROPY_SIPHON',
    name: 'Sifón de Entropía del Vacío',
    description: 'Convierte el 15% del daño infligido en cristales del vacío y recarga escudos al instante.',
    rarity: 'VOID',
    category: 'CORE',
    icon: '🌌',
    maxLevel: 1,
    behaviorTag: 'VOID_LEECH',
  },
  {
    id: 'DIMENSIONAL_ECHO',
    name: 'Eco Fantasma Dimensional',
    description: 'Despliega una nave espectral sombría que replica el 60% de tus disparos.',
    rarity: 'VOID',
    category: 'CORE',
    icon: '👤',
    maxLevel: 1,
    behaviorTag: 'SHADOW_TWIN',
  },
];

export const SECRET_SYNERGIES: SynergyDef[] = [
  {
    id: 'PLASMA_STORM',
    name: 'Tormenta de Plasma',
    description: 'Los disparos del Cañón de Pulsos dejan vórtices eléctricos residuales que electrocutan enemigos.',
    weaponA: 'PLASMA_BLASTER',
    weaponB: 'TESLA_COIL',
    discovered: false,
    effect: 'Los impactos de plasma generan campos de choque eléctrico permanentes.',
  },
  {
    id: 'MISSILE_SWARM',
    name: 'Enjambre en Racimo',
    description: 'Los cohetes se fragmentan en 3 microflechas explosivas al detonar.',
    weaponA: 'MISSILE_PODS',
    weaponB: 'SPREAD_SHOT',
    discovered: false,
    effect: 'Los misiles despliegan metralla explosiva tras el impacto.',
  },
  {
    id: 'ANNIHILATOR_BEAM',
    name: 'Rayo Aniquilador',
    description: 'Los proyectiles del Cañón de Riel detonan explosiones de plasma en cascada a lo largo de su trayectoria.',
    weaponA: 'RAILGUN',
    weaponB: 'PLASMA_BLASTER',
    discovered: false,
    effect: 'La línea de perforación estalla con detonaciones en cadena.',
  },
  {
    id: 'GUARDIAN_NETWORK',
    name: 'Red de Guardianes',
    description: 'Los drones de escolta se enlazan mediante rayos láser continuos que calcinan a cualquier intruso.',
    weaponA: 'COMBAT_DRONES',
    weaponB: 'TESLA_COIL',
    discovered: false,
    effect: 'Los drones forman una barrera láser perimetral de alta potencia.',
  },
];

export const RARITY_COLORS: Record<Rarity, {
  border: string;
  badge: string;
  glow: string;
  text: string;
  bgGradient: string;
}> = {
  COMMON: {
    border: 'border-slate-500/40',
    badge: 'text-slate-300',
    glow: 'rgba(148, 163, 184, 0.2)',
    text: 'text-slate-100',
    bgGradient: 'from-slate-900/90 via-slate-800/80 to-slate-900/90',
  },
  RARE: {
    border: 'border-cyan-500/60',
    badge: 'text-cyan-400',
    glow: 'rgba(6, 182, 212, 0.4)',
    text: 'text-cyan-100',
    bgGradient: 'from-cyan-950/90 via-slate-900/80 to-cyan-950/90',
  },
  EPIC: {
    border: 'border-purple-500/70',
    badge: 'text-purple-400',
    glow: 'rgba(168, 85, 247, 0.45)',
    text: 'text-purple-100',
    bgGradient: 'from-purple-950/90 via-slate-900/80 to-purple-950/90',
  },
  LEGENDARY: {
    border: 'border-amber-400/80',
    badge: 'text-amber-400',
    glow: 'rgba(251, 191, 36, 0.55)',
    text: 'text-amber-100',
    bgGradient: 'from-amber-950/90 via-slate-900/80 to-amber-950/90',
  },
  VOID: {
    border: 'border-fuchsia-500',
    badge: 'text-fuchsia-400',
    glow: 'rgba(217, 70, 239, 0.65)',
    text: 'text-fuchsia-100',
    bgGradient: 'from-fuchsia-950/95 via-purple-950/90 to-black',
  },
};
